"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os

from setuptools import setup


data_files = []
for file in os.listdir('image'):
    file = os.path.join('image', file)
    if os.path.isfile(file):
        data_files.append(file)

for file in os.listdir('sound'):
    file = os.path.join('sound', file)
    if os.path.isfile(file):
        data_files.append(file)

APP = ['src/main.py']
DATA_FILES = data_files
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
